### ISSUE TITLE
Restarting 

### ISSUE THREAD

**Issue by caseydonohue2** [ssilverman/QNEthernet#31] opened 2023-03-21 16:05 UTC
I am having an issue restarting the PHY.  I just about have it working but more often than not, when the chip is powered back up, everything is super slow.  In QNEthernet.cpp, I made a copy of end() and named it Restart().  The code is the same as end() except I commented out detaching the loop:

void EthernetClass::Restart()
{
    if (netif_ == nullptr) {
        return;
    }
    restarting = true;

    //if (loopAttached) {
    //    loopAttached = false;
    //    ethLoop.detach();
    //}

#if LWIP_MDNS_RESPONDER
    MDNS.end();
#endif  // LWIP_MDNS_RESPONDER

    DNSClient::setServer(0, INADDR_NONE);
    dhcp_release_and_stop(netif_);
    dhcpActive_ = false;
    netif_set_down(netif_);

    enet_deinit();
    netif_ = nullptr;
}

In my Teensy application, I call Restart and then the following:

        IPAddress pIP;
        pIP.fromString("192.168.1.40);
        IPAddress pNMIP;
        pNMIP.fromString("255.255.255.0");
        IPAddress pGWIP;
        pGWIP.fromString("192.168.1.1");
        qindesign::network::Ethernet.begin(pIP, pNMIP, pGWIP);

        Udp.begin(9000);

It appears to work fine.  The link is re-established and I am communicating.  However, communication is very slow. Occasionally, I can restart and I'm back up to speed.  Completely random.

Why restart the chip?  I have a Teensy in a pretty noisy environment and every week or two, the link drops (with NativeEthernet as well) and will not recover.  Disconnecting the Ethernet kit and reconnecting solves the symptom.  This solution also solves the symptom if we can figure out a way to recover at speed.  

Any ideas here?  Thanks!

**Comment by ssilverman** [comment] 2023-03-21 18:57
I know, and I've seen the same thing too. :( I've been trying to address that problem, but I haven't hit on the solution yet.

In fact, here's a snippet from a project of mine:
```c++
// Initializes Ethernet.
static bool initEthernet() {
  logger.info("[Main] Initializing Ethernet...");

  // This makes the restarted Ethernet really slow:
  // qneth::Ethernet.end();

  qneth::Ethernet.macAddress(ethernetMAC);
  logger.info("[Main] Ethernet MAC = "
              "%02" PRIx8 ":%02" PRIx8 ":%02" PRIx8
              ":%02" PRIx8 ":%02" PRIx8 ":%02" PRIx8,
              ethernetMAC[0], ethernetMAC[1], ethernetMAC[2],
              ethernetMAC[3], ethernetMAC[4], ethernetMAC[5]);
```

Do you know what I did instead? Restarted the whole thing (do a search on the PJRC forum or Google to learn more):
```c++
  SCB_AIRCR = 0x05FA0004;
```

Maybe this could be mitigated by a better shutdown or startup sequence. But I don't know if it's really this, or if maybe the magnetics in the Ethernet jack itself hold onto some "charge" or something. I'm grasping at straws here. Or maybe more delays?

I'm open to any assistance with initialization/deinitialization of the PHY and Ethernet system.

**Comment by caseydonohue2** [comment] 2023-03-21 19:03
Interesting.  Unfortunately, restarting the whole thing is not an option for me as I have other time-critical things happening as well.  However, I did come up with a rickety work-around.  When I see the link drop, I perform the "Restart".  After the link, I time 3 UDP transactions.  If they are slow, I "restart" again.  I continue this until I am back at speed.  As I mentioned earlier, it's completely random and eventually I get lucky and I'm back at speed.  Considering this only happens once every week or two, this rickety solution will probably do the trick.  However, if you discover anything new with this, please let me know so I can apply a better band-aid.  Thanks!

**Comment by ssilverman** [comment] 2023-03-21 19:33
I'm curious, what is the link speed you see upon restart and after link-up? See `Ethernet.linkSpeed()`.

**Comment by caseydonohue2** [comment] 2023-03-21 19:42
Ethernet.linkSpeed() returns 100 every time whether communication is fast or slow.  Yes, I tried a delay between the end and begin.  Same result.

**Comment by ssilverman** [comment] 2023-03-21 19:44
Thanks. If you don't mind, I'm going to keep this issue open to remind myself it's still here. I should have opened one myself when I first noticed the slowness...

**Comment by caseydonohue2** [comment] 2023-03-21 19:44
Works for me.  Thanks for looking into this!

**Comment by ssilverman** [comment] 2023-03-22 13:49
I had meant to ask about that: am I correct in saying that unplugging and then plugging it back in that ribbon cable for the Ethernet kit makes the traffic after a Reset() call go back to normal speed? What is the specific sequence of events that makes unplugging the Ethernet kit work with the reset? Or did you mean it was without a reset. I.e. _instead_ of Reset(), you unplug and then plug back in that ribbon cable?

**Comment by caseydonohue2** [comment] 2023-03-22 13:59
Actually, unplugging the ribbon cable during long communication results in continued long communication when plugging the ribbon cable back in.  There is no sequence of events I can see that makes unplugging return back to speed.  The only resolution I see is either cycling power on the Teensy or continuing to perform resets until the delay goes away.  

Yes, I'm not understanding where the 500 milliseconds is coming from either.  My host software polls the Teensy every 10 milliseconds:  the Teensy receives about 100 bytes from host and responds to host  with about 100 bytes.  The host waits 10 milliseconds and performs another transaction.  I all this "cycle time."  The entire transaction takes about 15 milliseconds (10 milliseconds of sleep and 5 milliseconds to actually perform the transaction).  It is very reliable and only varies by around 1 millisecond.

After the reset, some of these transactions take EXACTLY 500 milliseconds later.  It's not coming from the host side.  That's the mystery.  I just find it interesting that it is exactly 500 milliseconds of delay.

**Comment by caseydonohue2** [comment] 2023-03-22 14:02
So upon receiving the data from host, I evaluate:

            ATransactionHasBeenCompleted = true;
            if (SamplesCollected >= 0)
            {
                SampleAccumulator += CycleTime;
                if (CycleTime > 500)
                    AtLeastOne500Sample = true;
            }
            ++SamplesCollected;
            if (SamplesCollected >= 3)
            {
                AverageCycleTime = SampleAccumulator / SamplesCollected;
                if (!AtLeastOne500Sample)
                    AverageCycleTime = 0;
                //Serial.println(AverageCycleTime);
                SampleAccumulator = 0;
                SamplesCollected = 0;
            }
            //Serial.println(CycleTime);
            CycleTime = 0;

    // CheckLink is an elapsedMillis, allow 10 seconds between resets due to link drops
    if ((CheckLink >= 10000 && qindesign::network::Ethernet.linkState() != 1) || (ATransactionHasBeenCompleted && AverageCycleTime > 100))
    {
        Serial.println("Restarting Ethernet");
        qindesign::network::Ethernet.Restart();
        Connect();
    }

**Comment by caseydonohue2** [comment] 2023-03-22 14:03
Oh I see.  See above code.  Basically, I'm timing the time it takes to receive data from my host application.

**Comment by caseydonohue2** [comment] 2023-03-22 14:04
CycleTime is an elapsedMillis btw.

**Comment by ssilverman** [comment] 2023-03-22 14:05
You’re still not showing me what your’re timing.

**Comment by caseydonohue2** [comment] 2023-03-22 14:07
int packetSize = Udp.parsePacket();
    if (packetSize > 0)   
	ATransactionHasBeenCompleted = true;
        if (SamplesCollected >= 0)
        {
            SampleAccumulator += CycleTime;
            if (CycleTime > 500)
                AtLeastOne500Sample = true;
        }
        ++SamplesCollected;
        if (SamplesCollected >= 3)
        {
            AverageCycleTime = SampleAccumulator / SamplesCollected;
            if (!AtLeastOne500Sample)
                AverageCycleTime = 0;
            //Serial.println(AverageCycleTime);
            SampleAccumulator = 0;
            SamplesCollected = 0;
        }
        //Serial.println(CycleTime);
        CycleTime = 0;
    end if

I'm timing the time between:
 if (packetSize > 0)

**Comment by caseydonohue2** [comment] 2023-03-22 14:09
So every time I receive anything over UDP, I capture the time elapsed and restart the timer.  Sorry, there's tons of code so I'm trying to trim out enough stuff to show what is going on.

**Comment by ssilverman** [comment] 2023-03-22 14:10
Please wrap your code in a code fence (triple-backtick).

I’m getting a little frustrated here because I have no idea what is adding 500 ms. I’m not asking for the cause because we don’t know that. I’m asking which lines of code are taking 500 ms more. It’s a good clue, but not helpful if I don’t know what you’re wrapping.

**Comment by ssilverman** [comment] 2023-03-22 14:20
For example:
1. Start timer
2. Code A
3. Code B
4. End timer and print elapsed time

If printing the elapsed time shows 500ms greater than a previous print then we know “Code A” _and_ “Code B” is taking 500ms longer than before. We don’t know _what specifically inside of_ “Code A” and “Code B” is taking longer, but we know that somewhere inside is taking longer.

I want to know what lines of your code are equivalent to “Code A” and “Code B”. For example, is it “read audio from external device” and “send a packet over UDP”? Is it “blink an LED and turn on a GPIO”? Is it “blink an LED and turn on a GPIO” and then “check for TCP data”? _If_ the code you’re wrapping includes _QNEthernet_ calls, then there’s a possibility the stack is taking 500ms longer. However, if the code you’re wrapping does _not_ include _QNEthernet_ calls then the Ethernet stack _isn’t_ the code that’s adding 500ms.

I still don’t know what code you’re wrapping so that you can time it.

**Comment by caseydonohue2** [comment] 2023-03-22 14:25
So if I Serial.println(CycleTime), that's where I see the added delay of exactly 500 milliseconds.

**Comment by ssilverman** [comment] 2023-03-22 14:29
_Where_ do you call Serial.println(CycleTime)? The elapsedMillis type consults the current millis() time each time it’s accessed. This means that where in the code you’ve printed the value is important.

**Comment by caseydonohue2** [comment] 2023-03-22 14:33
```
void clsHostCommunication::Connect()
{
    IPAddress pIP;
    pIP.fromString(g.Parameters.IPAddress);
    IPAddress pNMIP;
    pNMIP.fromString("255.255.255.0");
    qindesign::network::Ethernet.begin(pIP, pNMIP, INADDR_NONE);
    CheckLink = 0;
    SamplesCollected = -1;
    SampleAccumulator = 0;
    AverageCycleTime = 0;
    AtLeastOne500Sample = false;
    ATransactionHasBeenCompleted = false;
}


void clsHostCommunication::Run() // called by ino loop()
{
    if ((CheckLink >= 10000 && qindesign::network::Ethernet.linkState() != 1) || (ATransactionHasBeenCompleted && AverageCycleTime > 100))
    {
        Serial.println("Restarting Ethernet");
        qindesign::network::Ethernet.Restart();
        Connect();
    }

    int packetSize = Udp.parsePacket();
    if (packetSize > 0)
    {
        Udp.read(InBuffer, MaxIncomingBuffer);
        ATransactionHasBeenCompleted = true;
        if (SamplesCollected >= 0)
        {
            SampleAccumulator += CycleTime;
            if (CycleTime > 500)
                AtLeastOne500Sample = true;
        }
        ++SamplesCollected;
        if (SamplesCollected >= 3)
        {
            AverageCycleTime = SampleAccumulator / SamplesCollected;
            if (!AtLeastOne500Sample)
                AverageCycleTime = 0;
            SampleAccumulator = 0;
            SamplesCollected = 0;
        }
        Serial.println(CycleTime);
        CycleTime = 0;

        // Handle the data that just arrived and respond
    }
}
```

Sorry, I had already removed that before pasting.  As shown above, the Serial.println(CycleTime) occurs right before resetting the elapsedMillis CycleTime to 0.

**Comment by ssilverman** [comment] 2023-03-22 14:39
Thank you. That’s what I needed. It looks like you’re starting the timer (setting to zero) after processing a packet and then ending the timer when you’re printing it. This essentially includes almost the entirety of your program. :)

Would you mind narrowing that range to figure out which part of the code takes that 500ms longer?

It’s a good clue and I appreciate you noticing it. One of the things that comes to mind is perhaps one of the internal lwIP timers. Not sure if that’s related, but it could be. I’d love to know if it’s your code that’s taking 500ms longer or somewhere in the networking code.

**Comment by ssilverman** [comment] 2023-03-22 14:45
A subtle note: `Ethernet.linkStatus()` should really be compared with one of the `EthernetLinkStatus` enum values. Your check against `1` Isn’t necessarily incorrect because `LinkON` is `1` in my library, but that’s not guaranteed by https://www.arduino.cc/reference/en/libraries/ethernet/ethernet.linkstatus/.

There’s also a Boolean-valued `Ethernet.linkState()` function.

**Comment by caseydonohue2** [comment] 2023-03-22 14:56
Yeah, sorry about that.  I should have just trimmed out the functionality of it the first time.  

You bring up an excellent point about where to search for the delay!  It just occurred to me that my host software sends the data and waits up to 500 milliseconds for a response.  If no response, it simply sends the data again.  I just bumped that up to 1000 milliseconds and sure enough, now we're outputting 1014 milliseconds from CycleTime.  Therefore, the delay is coming from my host software.

So, the problem is now a different problem.  The problem isn't a delay that happens every 1 to 4 transactions after a reset.  The problem is Udp.parsePacket() is not detecting any data receipt every 1 to 4 transactions.  This makes more sense.  Eventually, after enough resets, it stops missing transactions.

**Comment by ssilverman** [comment] 2023-03-22 15:04
I want to rule out something else. Could you give the `EthernetUDP` constructor a queue value, say, of 64 or 128? In my experience, when packets come in really fast, it’s possible to miss them if the processing time is just a little bit behind.

For example, instead of this:
```c++
EthernetUDP udp;
```
Do this:
```c++
EthernetUDP udp(64);
```

The internal queue buffers incoming packets, up to the queue size. The default is 1.

**Comment by caseydonohue2** [comment] 2023-03-22 15:10
![Udp](https://user-images.githubusercontent.com/104102763/226948706-c3bdf329-9a89-4f87-90be-3230435ba9d5.png)

My constructor doesn't allow me to take any parameters.

**Comment by ssilverman** [comment] 2023-03-22 15:14
https://github.com/ssilverman/QNEthernet/blob/59f2db2a29a6cac2138b77e949f60bb07b21a3a8/src/QNEthernetUDP.h#L31

Does it compile? I’ve seen my IDE disagree with the compiler sometimes.

**Comment by caseydonohue2** [comment] 2023-03-22 15:22
Well, now that you mention it, probably not.  Was pulled from Ardunio library manager, 0.19.0.  Let me update...

**Comment by caseydonohue2** [comment] 2023-03-22 15:23
Weird.  The library manager downloaded 0.19.0 but let me see what I actually have.

**Comment by ssilverman** [comment] 2023-03-22 15:27
Once you've tried and verified with the latest _QNEthernet_ with a UDP queue, try this next:
1. Stop all UDP sockets (`udp.stop()`)
2. `Ethernet.end()`
3. `Ethernet.begin(...)`
4. Re-begin all UDP sockets.

I wonder if not stopping and restarting the UDP sockets relates to the problem...

**Comment by caseydonohue2** [comment] 2023-03-22 16:17
Yes, I have 0.19.0.  I tried the queueSize of 64.  Same result.  About to try udp.stop() and re-begin...

**Comment by caseydonohue2** [comment] 2023-03-22 16:26
Udp.stop(), Ethernet.end(), Ethernet.begin(pIP, pNMIP, INADDR_NONE), Udp.begin(9000): same result.

**Comment by ssilverman** [comment] 2023-03-22 16:47
> Yes, I have 0.19.0. I tried the queueSize of 64. Same result. About to try udp.stop() and re-begin...

By "same result", do you mean "can't compile"? Or do you mean "delays are happening"?

**Comment by ssilverman** [comment] 2023-03-23 06:57
I figured out why your commenting out the `ethLoop.detach();` block was necessary. That call doesn't work properly without an `ethLoop.clearEvent()` just before it. I fixed this locally and will be pushing to `master` soon.

**Comment by ssilverman** [comment] 2023-04-04 00:24
@caseydonohue2 Could you try changing, in _lwip_t41.c_, the delays from 2µs and 5µs to 25µs and 2ms? Like this:
```c++
delayMicroseconds(25);
delay(2);
```

Let me know if this improves things.

**Comment by caseydonohue2** [comment] 2023-04-04 00:29
Sure.  I'll try it in the morning.

**Comment by ssilverman** [comment] 2023-04-09 20:15
Thanks for trying that. I'd also like to see what happens for you if you comment out `dhcp_inform(netif_);` in _QNEthernet.cpp:begin(ipaddr, netmask, gw)_.

I've been going through all this from time to time.

**Comment by caseydonohue2** [comment] 2023-04-10 13:27
Interesting.  That actually made it worse.  Typically, if the link drops, it takes 1 to 3 restart attempts to get it back up to speed.  There are always outliers.  But 6 attempts it the worst I've seen.  With dhcp_inform(netif_); commented out, I am seeing cases where it requires many more restart attempts to get it back up to speed.  Ie, my last link drop required 83 restart attempts with this line of code commented out.

**Comment by ssilverman** [comment] 2023-04-10 16:19
Huh. That’s not what I was expecting to hear. :) I just released v0.20.0 with dhcp_inform() commented out. Would you mind trying this new version both with and without that line uncommented? There are some other changes related to my fix attempts for this issue.

**Comment by caseydonohue2** [comment] 2023-04-10 20:07
I updated to 0.20.0.  Behavior is the same.  With dhcp_inform(netif_) commented out, a very large number of restarts are usually required to get back up to speed.  Uncommenting that line goes back to previous behavior, only requiring 1 to 3 restarts to get back up and running.  Very strange.

I did notice that Ethernet.end() now functions correctly for restarting.

**Comment by ssilverman** [comment] 2023-04-10 20:08
Thanks for trying these things out. I'm stumped...

**Comment by caseydonohue2** [comment] 2023-04-10 20:45
Yes, that is correct.  From my perspective, my host software sends data to the Teensy, expecting data to be returned immediately.  There is a 500 millisecond watchdog so if the Teensy does not respond within that time, the host just discards the transaction and creates a new one.  After a restart, my response times will look something like:

millseconds:
2064 (restarting the PHY)
514 (timeout + 1 good)
14 (good)
14 (good)
514 (timeout + 1 good)
14 (good)
514 (timeout + one good)

So I can clearly see those timeouts.  After I see a couple of them, I restart again and again until eventually, I will see
14
14
14
15
14... back to normal.

So yes, functioning but to me, it doesn't seem "slow".  It seems more like it is simply not detecting the data being sent from host.  Sometimes it reacts.  Sometimes it doesn't.  Eventually, after enough restarts, it will go back to correctly handling every transaction.  I find it really strange that by restarting it enough times, I can eventually get back to the flawless state and once I'm there, it'll run just fine forever until I drop the link again.

Therefore, I think I agree.  The PHY is not relaying packets to the stack.

**Comment by ssilverman** [comment] 2023-04-11 02:47
I'm not sure it will make much of a difference, but try this; in _lwip_t41.c_, change:

```c++
delay(2);  // T2, reset to SMI ready
```

To:

```c++
delay(50);  // T4, power-up stabilization time
```

I'm going to come up with more things to try, such as other types of PHY reset (its registers). Thanks for engaging more to pursue fixing this.

**Comment by ssilverman** [comment] 2023-04-11 03:23
I'm trying another thing: I've made the PHY startup much more conservative. See this branch:
https://github.com/ssilverman/QNEthernet/tree/phy-reset

Try this code; if it works (fingers crossed) we then can attempt to whittle it down until we find the change that fixes it.

**Comment by ssilverman** [comment] 2023-04-11 03:41
I'm now diving into all the registers to see if there's some weird state...

**Comment by caseydonohue2** [comment] 2023-04-11 13:08
> delay(50);  // T4, power-up stabilization time

Same behavior.


> I'm trying another thing: I've made the PHY startup much more conservative. See this branch: https://github.com/ssilverman/QNEthernet/tree/phy-reset
> 
> Try this code; if it works (fingers crossed) we then can attempt to whittle it down until we find the change that fixes it. I'm being optimistic here...

Same behavior.



> static void enet_isr() {
>   if ((ENET_EIR & ENET_EIR_RXF) != 0) {
>     ENET_EIR = ENET_EIR_RXF;
>     atomic_flag_clear(&s_rxNotAvail);
>     asm volatile ("dsb":::"memory");
>   }
> }

Same behavior.


And still, uncommenting dhcp_inform() in QNEthernet.cpp is night and day in performance.  I was thinking maybe dhcp_inform() was taking a certain amount of time to execute so I tried putting a delay(10) and then a delay(100) in its place but the poor performance continued.  Something about this dhcp_inform() seems to be pointing in the right direction.

Reaching for straws, I tried the following:
 ```
    dhcp_inform(netif_);
    delay(a variety of times from 10 to 2000);
    dhcp_inform(netif_);
```
This performs as bad as having dhcp_inform() commented out.

````
    dhcp_inform(netif_);
    delay(a variety of times from 10 to 2000);
```
The additional delay seems to have no effect.

**Comment by ssilverman** [comment] 2023-04-11 15:53
I'm not sure what else I can do about the PHY reset, but I had another thought. What if it isn't the PHY, but the MAC layer on the processor? I'm going to dive into that now...

**Comment by ssilverman** [comment] 2023-04-17 22:41
I asked for some help here: https://forum.pjrc.com/threads/72608-Seeking-some-assistance-with-QNEthernet-restart

**Comment by caseydonohue2** [comment] 2023-04-18 12:45
Fingers crossed.  I'll keep my eye on it.  Thanks!

**Comment by ssilverman** [comment] 2023-04-27 23:59
I just had another idea: What about, instead of `Ethernet.end()`, you just reset the PHY? i.e. take it down and bring it back up, per parts of the _lwip_t41.c_ code.

**Comment by caseydonohue2** [comment] 2023-04-28 00:02
Sure.  Tell me what to do and I'll try it.

**Comment by ssilverman** [comment] 2023-04-28 03:10
Unfortunately, my "soft reset" experiments failed, and the system doesn't come back up where it can receive packets reliably. I haven't tried hard-resetting the PHY yet, but I suspect that won't work either. I'm exploring if there's a way on the Teensy's processor to reset the MII/RMII somehow...

**Comment by ssilverman** [comment] 2023-04-28 03:18
This is extremely vexatious.

**Comment by caseydonohue2** [comment] 2023-04-28 12:55
I can understand that.   There's not much worse than a nagging problem.  Please let me know what I can do to help in regards to further testing or whatever.  Thanks!

**Comment by ssilverman** [comment] 2023-08-24 02:24
Here's an update. I try to solve this once every so often but fail miserably. The issue is reproducible when running all the unit tests. _test_udp_ and _test_client_ always fail with an unreceived SNTP message and a DHCP failure, respectively. Running these tests by themselves always seems to work.

I've:
1. Explored _memp_ stats while running the tests, specifically for UDP,
2. Explored timer stats while running the tests,
3. Tried freeing all pending timers inside `enet_deinit()`, and
4. Tried to see what exactly I can undo that `lwip_init()` does (that function can only be called once).

Still no luck. :(

**Comment by ssilverman** [comment] 2023-11-12 04:03
I just added a macro gate around the code in `Ethernet.end()` that shuts down the PHY and Ethernet. I don't much like this solution, but it'll have to do for now. @caseydonohue2 if you're still following this thread, please give it another try. If it still doesn't work for you, I'll add a PHY software reset to just after where it gets initialized.

**Comment by caseydonohue2** [comment] 2023-11-14 14:39
I am getting the following errors when I attempt to compile:

lwip_t41.c: In function check_link_status
 
lwip_t41.c: 901:7: error: expected expression before '[' token
   [[fallthrough]]
 
lwip_t41.c: 901:9: error: 'fallthrough' undeclared (first use in this function)
   [[fallthrough]]
lwip_t41.c:901: note  each undeclared identifier is reported only once for each function it appears in
 
lwip_t41.c: 910:7: error: expected expression before '[' token
   [[fallthrough]]
 
lwip_driver.h:18: In file included from
lwip_t41.c:11: from

**Comment by ssilverman** [comment] 2023-11-14 22:54
Which version of Teensyduino are you using to build? (And are you using PlatformIO?)

I've got the latest v1.58 equivalent, and it successfully with both C++14 and C++17 dialects.
Here's what the build shows:
```
PACKAGES: 
 - framework-arduinoteensy @ 1.158.0 (1.58) 
 - tool-teensy @ 1.158.0 (1.58) 
 - toolchain-gccarmnoneeabi-teensy @ 1.110301.0 (11.3.1)
```

**Comment by caseydonohue2** [comment] 2023-11-15 20:34
This solved the problem!

**Comment by ssilverman** [comment] 2023-11-15 23:10
I'm so glad! Note that unless the `QNETHERNET_INTERNAL_END_STOPS_ALL` macro is defined, neither the PHY nor Ethernet hardware is shut down. I just couldn't get reception back to speed when those are shut down, and I can't seem to figure out why; I've been making attempts for quite a while. You can see this effect when running all the the tests. About 2.5 minutes when defining that macro, and about 20 seconds when not defining that macro.
Test command: `pio test -e teensy41-test -vv -f test_ethernet`

Whatever's happening now on your system seems to be compatible with my latest changes _without_ having to restart the PHY.

I'll close this issue for now. If you see anything related pop up again, feel free to comment here and/or reopen it.

**Closed by ssilverman** 2023-11-15 23:10 UTC
Labels: bug
