### ISSUE TITLE
warning: type 'struct EthernetClient' violates the C++ One Definition Rule [-Wodr]

### ISSUE THREAD

**Issue by Stevenlawrencehoriba** [ssilverman/QNEthernet#45] opened 2023-06-13 14:46 UTC
can you explain why we get this Warning/error and few others when compiling with the latest PlatformIO , even though its in its own namespace? and being used with a fully qualified namespace. It seems to refer to 

type of '__ct_comp ' does not match original declaration [-Wlto-type-mismatch]

**Comment by Stevenlawrencehoriba** [comment] 2023-06-13 14:47
.pio\libdeps\teensy41\QNEthernet\src\QNEthernetClient.h:31:7: note: a different type is defined in another translation unit
   31 | class EthernetClient : public Client {

**Comment by ssilverman** [comment] 2023-06-13 15:20
I don’t think LTO works yet.

For your second comment, maybe you’re trying to also build in a different Ethernet library, or somehow building in this one twice?

**Comment by ssilverman** [comment] 2023-06-13 15:21
I would check what’s inside both your project-specific library folder and your system-wide library folder to see what’s being built in.

**Comment by Stevenlawrencehoriba** [comment] 2023-06-14 08:24
I only have your library in PlatformIO.ini, and FreeRTOS port. with NativeEthernet BUT, that's in a different namespace, so there are no duplicates, other than the NAME Ethernet and EthernetServer, (again differnt namespaces, All qualified in the code where used?) Unless NativeEthernet, is in root namespace which maybe the issue... I will check

**Comment by ssilverman** [comment] 2023-06-14 14:49
Why would you want to build in both NativeEthernet and _QNEthernet_? There’s both C and C++. I’ve never tried it, but I would expect there to be conflicts.

Other question: Are you building with LTO?

**Comment by Stevenlawrencehoriba** [comment] 2023-06-15 07:40
I have checked all the libraries and its not even bringing in NativeEthernet. i am not including it.  As stated above using namespace per type should not cause it anyway.  This is enabled -DTEENSY_OPT_FASTER_LTO i dont know if that is doing it, (next look around) build flags are -Wformat=1 -fno-strict-aliasing -Wno-deprecated -Wno-unused-variable -Wno-unused-parameter. QNEthernet is working as expected. I cant use NativeEthernet, because it delays in the read too long , and expects constant data stream to keep it alive ( i can change it and use it, but dont want the hastle with libraires, as other people would have make the same changes). It is using this https://github.com/tsandmann/platform-teensy.git, however and this https://github.com/tsandmann/freertos-teensy.git. I think its something to do with LTO, I have seen on other forums where there  is a bug in the gcc compilier , which has been fixed on version 7 something, it may not have filtered down to the arm one?

**Comment by Stevenlawrencehoriba** [comment] 2023-06-15 08:16
I can confirm the code still works on the platform, may not be optimized though

**Comment by ssilverman** [comment] 2023-06-15 20:42
See: https://github.com/ssilverman/QNEthernet/issues/45#issuecomment-1589530310

I don’t believe LTO is supported yet. Try whatever optimization flags you need, but without the “LTO” part.

**Comment by ssilverman** [comment] 2023-06-20 15:16
Does it work for you if you don’t use LTO?

**Comment by ssilverman** [comment] 2023-06-22 15:45
I suspect it’a problem with LTO. Closing for now; please reopen if the issue is still there without an LTO build.

**Closed as completed by ssilverman** 2023-06-22 15:45 UTC
Labels: question
