### ISSUE TITLE
 error: 'MEMP_IGMP_GROUP' undeclared (first use in this function)        memp_free(MEMP_IGMP_GROUP, group);

### ISSUE THREAD

**Issue by Mike0675** [ssilverman/QNEthernet#16] opened 2022-07-14 16:22 UTC
Hi, Im using Sloeber/Eclipse.

QNEthernet don´t compile .

C:\Sloeber\arduinoPlugin\libraries\QNEthernet\0.14.0\src\lwip\ipv4\igmp.c:624:17: error: 'MEMP_IGMP_GROUP' undeclared (first use in this function)
       memp_free(MEMP_IGMP_GROUP, group);

**Comment by ssilverman** [comment] 2022-07-14 18:50
It's defined on line 98 of `src/lwip/priv/memp_std.h`: https://github.com/ssilverman/QNEthernet/blob/4c2c999289c906764132b9bb22f1ba77c482d629/src/lwip/priv/memp_std.h#L98

It's likely your environment doesn't include or know how to locate the include files. You might need to point it to `src` as an include directory. The reason this is structured this way is to accommodate the Arduino build from the Arduino IDE.

`lwip/ipv4/igmp.c` includes `lwip/stats.h` includes `lwip/memp.h` includes `lwip/priv/memp_std.h`.

**Comment by Mike0675** [comment] 2022-07-14 20:54
The Problem is MEMP_IGMP_GROUP not MEMP_NUM_IGMP_GROUP?
Searching all Files i can´t find MEMP_IGMP_GROUP?

**Comment by ssilverman** [comment] 2022-07-14 21:00
`MEMP_IGMP_GROUP` is defined as an enum by a macro. Unfortunately, it's not explicitly defined in one step. If your includes are set up correctly, it should compile. If it's not compiling then the build system you're using hasn't found the necessary includes.

**Comment by jantje** [comment] 2022-07-15 18:02
@ssilverman 
Hi Jantje from Sloeber here. It seems to me the build command is missing defines. Does your library need command line level defines? And if so, how are they provided?
Thanks

```
"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy/../tools/arm/bin/arm-none-eabi-gcc" -c -O1 -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=156 -DARDUINO=10812 -DARDUINO_TEENSY41 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_GERMAN -I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\cores\teensy4" -I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\Wire" -I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\Wire\utility" -I"C:\Sloeber\arduinoPlugin\libraries\Adafruit_MCP23017_Arduino_Library\2.1.0\src" -I"C:\Sloeber\arduinoPlugin\libraries\Adafruit_BusIO\1.11.6" -I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\SPI" -I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\FNET\src" -I"C:\Sloeber\arduinoPlugin\libraries\Functional-Vlpp\1.0.2\src" -I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\SD\src" -I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\SdFat\src" -I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\Time" -I"C:\Sloeber\arduinoPlugin\libraries\AsyncUDP_Teensy41\1.2.1\src" -I"C:\Sloeber\arduinoPlugin\libraries\AsyncWebServer_Teensy41\1.4.1\src" -I"C:\Sloeber\arduinoPlugin\libraries\QNEthernet\0.14.0\src" -MMD -MP -MF"libraries\QNEthernet\src\lwip\ipv4\igmp.c.d" -MT"libraries\QNEthernet\src\lwip\ipv4\igmp.c.o" -D__IN_ECLIPSE__=1 "C:\Sloeber\arduinoPlugin\libraries\QNEthernet\0.14.0\src\lwip\ipv4\igmp.c" -o "libraries\QNEthernet\src\lwip\ipv4\igmp.c.o"
C:\Sloeber\arduinoPlugin\libraries\QNEthernet\0.14.0\src\lwip\ipv4\igmp.c: In function 'igmp_stop':
C:\Sloeber\arduinoPlugin\libraries\QNEthernet\0.14.0\src\lwip\ipv4\igmp.c:179:15: error: 'MEMP_IGMP_GROUP' undeclared (first use in this function)
memp_free(MEMP_IGMP_GROUP, group);
```

**Comment by ssilverman** [comment] 2022-07-15 19:05
Have you tried building one of the simple _QNEthernet_ examples first?

**Comment by ssilverman** [comment] 2022-07-15 21:45
@jantje Thanks for the explanation, and these are totally fine questions, no worries. I do understand that you have less context. Here's a list to help you fill in some details as I see them:
1. `MEMP_IGMP_GROUP` is actually defined as an enum value whose name is constructed by a macro via something like `MEMP_##name`. That's deep in lwIP and I don't personally know a bunch of the stuff that's in there. That's the "line 98" reference you see above. (https://github.com/ssilverman/QNEthernet/blob/4c2c999289c906764132b9bb22f1ba77c482d629/src/lwip/priv/memp_std.h#L98)
2. I'm 100% certain that programs that use this library build and run fine on the Arduino IDE and with PlatformIO on VSCode.
3. If Sloeber does anything different than what those two platforms do then that might be the reason the build isn't working. It may be some assumptions being made regarding locations or something. But GCC is used, and I know command-line builds are possible, so maybe it's just something missing from the build commands.
4. I believe Teensyduino (also included in the PlatformIO system) contains a Makefile somewhere that has all the steps, but I don't recall ever diving into it.
5. The Teensy Forum, I believe, probably in addition to some websites, contains some discussion about command-line builds that may contain some more clues as to why this build is failing.

I hope this helps.

**Comment by ssilverman** [comment] 2022-07-15 22:13
I just did a verbose build using PlatformIO (https://community.platformio.org/t/show-actual-build-command-using-platformio-ini/21038) and I see as the build command for `igmp.c`:
```
arm-none-eabi-gcc -o .pio/build/teensy41/src/lwip/ipv4/igmp.c.o -c -Wall -ffunction-sections -fdata-sections -mthumb -mcpu=cortex-m7 -nostdlib -fsingle-precision-constant -mfloat-abi=hard -mfpu=fpv5-d16 -O2 -DPLATFORMIO=60101 -D__IMXRT1062__ -DARDUINO_TEENSY41 -DUSB_SERIAL -DARDUINO=10805 -DTEENSYDUINO=156 -DCORE_TEENSY -DF_CPU=600000000 -DLAYOUT_US_ENGLISH -Iinclude -Isrc -I/Users/shawn/.platformio/packages/framework-arduinoteensy/libraries/Entropy -I/Users/shawn/.platformio/packages/framework-arduinoteensy/cores/teensy4 src/lwip/ipv4/igmp.c
```

Here are the differences:

Mine:
```
-fsingle-precision-constant
-O2
-DPLATFORMIO=60101
-DARDUINO=10805
-DCORE_TEENSY
-DLAYOUT_US_ENGLISH
-Iinclude
-Isrc
-I/my-home-directory/.platformio/packages/framework-arduinoteensy/libraries/Entropy
```

Yours:
```
-O1
-MMD
-DARDUINO=10812
-DLAYOUT_GERMAN
-I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\Wire"
-I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\Wire\utility"
-I"C:\Sloeber\arduinoPlugin\libraries\Adafruit_MCP23017_Arduino_Library\2.1.0\src"
-I"C:\Sloeber\arduinoPlugin\libraries\Adafruit_BusIO\1.11.6"
-I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\SPI"
-I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\FNET\src"
-I"C:\Sloeber\arduinoPlugin\libraries\Functional-Vlpp\1.0.2\src"
-I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\SD\src"
-I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\SdFat\src"
-I"C:\arduino-1.8.19-windows\arduino-1.8.19\hardware\teensy\avr\libraries\Time"
-I"C:\Sloeber\arduinoPlugin\libraries\AsyncUDP_Teensy41\1.2.1\src"
-I"C:\Sloeber\arduinoPlugin\libraries\AsyncWebServer_Teensy41\1.4.1\src"
-I"C:\Sloeber\arduinoPlugin\libraries\QNEthernet\0.14.0\src"
-MMD
-MP
-MF"libraries\QNEthernet\src\lwip\ipv4\igmp.c.d"
-MT"libraries\QNEthernet\src\lwip\ipv4\igmp.c.o"
-D__IN_ECLIPSE__=1
```

* `-fsingle-precision-constant`: Shouldn't matter
* `-DCORE_TEENSY`: You need this
* `-Iinclude`: I don't have anything in my `include` directory, so this shouldn't matter
* `-Isrc`: Include's _QNEthernet_'s `src` directory, which you have in your build command
* `-I/my-home-directory/.platformio/packages/framework-arduinoteensy/libraries/Entropy`: _QNEthernet_ depends on the `Entropy` library
* I don't know what all the other `-M` arguments are for in your build command.
* `-O2`: Out of curiosity, try this instead of your `-O1`

I would also try to build a basic _QNEthernet_ example without all the other includes (except for `Entropy`), just to minimize factors.

**Comment by jantje** [comment] 2022-07-15 23:26
I agree on your analysis
My input:

The -O1 and O2 are optimisation options and are selected in the optimize menu
Not having the Entropy library is a problem but not related to the current issue as there are no missing includes.
The -M and -MMP are to instruct make to create dependency trees. This allows make at  subsequent builds to identify source code files that need to be rebuild when headers are touched.

That leaves me with **-DCORE_TEENSY**. I have no clue where this comes from (nothing in platform.txt or boards.txt).
I compiled a sketch with Arduino IDE 1.8.15 with teensy duino 1.56 and the output did not contain -DCORE_TEENSY. 
I downloaded the latest arduino IDE 18.19 installed teensy duino on top and again no -DCORE_TEENSY
I guess this -DCORE_TEENSY is a platformio thing.
If -DCORE_TEENSY is needed I fear your library won't work in arduino IDE.
Can you test?

**Comment by ssilverman** [comment] 2022-07-15 23:50
I'm a little confused by your Arduino IDE comments. The _QNEthernet_ library has been working inside the Arduino IDE for about a year and a half. Why would you say it won't work? It's not new software. Try this:
1. Download and install the latest Arduino IDE and Teensyduino according to the instructions here: https://www.pjrc.com/teensy/td_download.html
2. Under Tools->Manage Libraries..., Install the QNEthernet library (note that if you do a search, lots of results will come up because I think a few other libraries use it) (also note that the latest version I've pushed is 0.14.0).
3. Restart the IDE so that it reloads any examples.
4. File->Examples->QNEthernet->SNTPClient
5. Click the checkbox (or Sketch->Verify/Compile) and you should get a successful build.

Teensyduino uses `CORE_TEENSY` in lots of places, just look inside a Teensyduino distribution and `grep` for it. Many libraries test for it. PlatformIO may just be adding it opportunistically for some other reason, but it's not critical. It's defined in `cores/teensy4/core_id.h`, in any case, and not defining it on the command-line compile is fine.

**Comment by jantje** [comment] 2022-07-16 13:36
As to your confusion: you said
>I just did a verbose build using PlatformIO

and
>-DCORE_TEENSY: You need this

as Arduino IDE does not put the -DCORE_TEENSY on the command line -nor does Sloeber- I come to the conclusion that one of the following statements is false

1. DCORE_TEENSY: You need this
2. It works in Arduino IDE

I assumed it was the second. Given the previous comment it seems to be the first.

>Another thought: Can you try to reorder your compiler options to match the order I have?

No. Platformio is free to do as they like but I'm following the Arduino IDE ordering based on the platform.txt file -adding specific Sloeber stuff-, But even then comparing command lines is difficult.

>Try and remember to drop any assumptions you have about argument behavior and even ordering. 

I understand you mean this positively but .... I'm an old guy with lots of years in C/C++. There is no need to point out these obvious things.

Here is where I think we are now:
I think it is safe to say that the answer to my question
>Does your library need command line level defines?

is no.

That leaves me with 2 possible issues to the build failure (both not related to your library nor Sloeber)
1) different arm-none-eabi-gcc version (I think unlikely)
2) Header mixup due to incompatibility with other library. (probably caused by Sloebers automatic way to include libraries based on missing includes)

I think 2 is the root cause. I'll investigate. If I find it I'll report the incompatible library.

**Comment by jantje** [comment] 2022-07-16 15:51
I did some tests here and here are my findings
There is no header mixup
This has nothing to do with your library. (For what I'm concerned you can close this issue)
Sloeber, platformio and teensyduino all generate different compile commands Teensyduino even using a different compiler.
I see teensyduino has some new functionality Sloeber has not yet implemented and platformio seems to ignore.

**Comment by ssilverman** [comment] 2022-07-16 15:58
Thanks.

**Closed by ssilverman** 2022-07-16 15:58 UTC

**Comment by jantje** [comment] 2022-07-16 19:40
FYI
I was on a completely wrong track. 
The problem is that Sloeber by default adds `#pragma once` to all headers at installation time.
This resulted in the macro expansion that happens in the second (or later) inclusion of mem_std.h file did not happen.
Therefore the macro didn't exists and as such the error OP got.

**Comment by ssilverman** [comment] 2022-07-16 19:41
@jantje thanks for adding the explanation and for your descriptions above.

**Comment by jantje** [comment] 2022-07-16 19:51
My brain has been going boom all day over this issue. Feels like I have been everywhere and nowhere.
I was really off track when I took the discovery command for the actual build command. 
Once back on track I still could not understand it. 
It is the first time this pragma once bites me seriously.

**Comment by ssilverman** [comment] 2022-07-16 20:09
Thanks again for diving in. I can say that I came away from this particular discussion having learned one or two things. :)
